### ISSUE TITLE
We should introduce a composable to define unique id's automagically to every html element. Ussage like the following:

### ISSUE THREAD

**Issue by FabianWilms** [it-at-m/muc-patternlab-vue#149] opened 2024-07-25 07:37 UTC
We should introduce a composable to define unique id's automagically to every html element. Ussage like the following:
```
const idForThisComponent = useUniqueID("muc-radio-button"); // return sth like muc-radio-button-123
```

vuetify uses similiar approach with some vue methods to generate the unique id's.

_Originally posted by @langehm in https://github.com/it-at-m/muc-patternlab-vue/issues/101#issuecomment-2249654886_

**Comment by langehm** [comment] 2024-07-25 08:04
Duplicate of #148

**Closed by langehm** 2024-07-25 08:04 UTC
